---
- name: Deploy JAR file to Tomcat
  hosts: webservers
  become: yes

  tasks:

    - name: Copy JAR file to Tomcat
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/job1/Application/target/mcapp-1.0.war
        dest: /opt/apache-tomcat-9.0.121/webapps/mcapp-1.0.war
        mode: '0644'

    - name: Stop Tomcat
      ansible.builtin.shell: /opt/apache-tomcat-9.0.121/bin/shutdown.sh
      ignore_errors: yes

    - name: Wait for Tomcat to stop
      ansible.builtin.pause:
        seconds: 5

    - name: Start Tomcat
      ansible.builtin.shell: /opt/apache-tomcat-9.0.121/bin/startup.sh
